disabled_rules:
  - trailing_comma
  - function_body_length

included:
  - SwiftUIShaders

line_length: 180

identifier_name:
  min_length: 1

file_length:
  warning: 550
  error: 1000

reporter: "xcode"
